# Generated by Django 5.2.6 on 2025-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_itemcarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
